# Generated by Django 3.2.4 on 2021-06-25 19:38

from django.db import migrations, models
import phonenumber_field.modelfields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=125, null=True, unique=True, verbose_name='email')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=125, null=True, region=None, unique=True, verbose_name='mobile')),
                ('full_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='full_name')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=user.models.upload_avatar)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
