# Generated by Django 3.2.4 on 2021-07-07 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_book_available'),
        ('shopcart', '0003_alter_shopcartitem_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCartItem',
            new_name='ShopCart',
        ),
    ]
