# Generated by Django 3.2.4 on 2021-07-10 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='Contact phone number', max_length=125, null=True, verbose_name='mobile')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=125, verbose_name='address')),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('In_delivery', 'In_delivery'), ('Delivery', 'Delivery')], default='PENDING', max_length=125)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
