# Generated by Django 3.2.4 on 2021-07-17 19:56

from django.db import migrations, models
import product.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_book_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to=product.utilities.category_image),
        ),
    ]
